version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: tes
      POSTGRES_PASSWORD: tes
      POSTGRES_DB: tes
    ports:
      - "5432:5432"
    volumes:
      - tes_db:/var/lib/postgresql/data
volumes:
  tes_db:
